package it.polito.ai.project.services.database.models;

public enum NotificationsType {
    CHILD_TAKEN,
    CHILD_ABSENT,
    CHILD_DELIVERED,
    COMPANION_STATEAVAILABILITY,
    COMPANION_REMOVEAVAILABILITY,
    COMPANION_CHOSEN,
    COMPANION_CONFIRMCHOSEN,
    COMPANION_REMOVECHOSEN,
    RACE_CONFIRMED,
    RACE_DELETED,
    RACE_STARTED,
    RACE_ENDED,
    STOP_REACHED,
    STOP_LEFT
}
